<?php

namespace Kontentblocks\Fields;

use Kontentblocks\Templating\CoreView;

/**
 * By default all sections and fields are organized in tabs,
 * which get generated by this class
 *
 * There may be different ways to organize in future releases
 * Instantiated by:
 * @see Kontentblocks\Fields\FieldManager::render()
 *
 * @package Fields
 * @since 0.1.0
 */
class FieldRendererTabs implements InterfaceFieldRenderer
{

    /**
     * Array of sections to render
     * @var array
     */
    protected $sections;

    /**
     * Unique identifier inherited by module
     * @var string
     */
    protected $baseId;

    /**
     * Instance data from module
     * Gets passed through to section handler
     * @var array
     */
    protected $data;

    /**
     * @var AbstractFieldController
     */
    protected $fieldController;


    /**
     * @param AbstractFieldController $fieldController
     */
    public function __construct( AbstractFieldController $fieldController )
    {
        $this->baseId = $fieldController->getEntity()->getId();
        $this->fieldController = $fieldController;
        $this->sections = $fieldController->sections;
    }

    /**
     * Wrapper to output methods
     * @return mixed|void
     */
    public function render( )
    {
        if (!is_array( $this->sections )) {
            return null;
        }
        $view = new CoreView(
            'renderer/tabs.twig', array(
                'structure' => $this->sections
            )
        );

        return $view->render();
    }

    /**
     * Renders the tab navigation markup
     */
    public function tabNavigation()
    {

        echo "<div class='kb_fieldtabs kb-field--tabs'>";
        echo "<ul>";


        /** @var AbstractFieldSection $section */
        foreach ($this->sections as $section) {

            if ($section->getNumberOfVisibleFields() > 0) {
                echo "<li><a href='#tab-{$section->getSectionId()}'>{$section->getLabel()}</a></li>";
            }
        }
        echo '</ul>';

    }

    /**
     * Renders the tab containers
     */
    public function tabContainers()
    {
        /** @var AbstractFieldSection $section */
        foreach ($this->sections as $section) {
            if ($section->getNumberOfVisibleFields() > 0) {
                echo "<div id='tab-{$section->getSectionId()}'>";
                $section->render();
                echo "</div>";
            } else {
                $section->render();
            }
        }
        echo "</div>";

    }

}
