<?php

namespace Kontentblocks\Fields;

/**
 * By default all sections and fields are organized in tabs,
 * which get generated by this class
 *
 * There may be different ways to organize in future releases
 * Instantiated by:
 * @see Kontentblocks\Fields\FieldManager::render()
 *
 * @package Fields
 * @since 1.0.0
 */
class FieldRendererTabs implements InterfaceFieldRenderer
{

    /**
     * Array of sections to render
     * @var array
     */
    protected $structure;

    /**
     * Unique identifier inherited by module
     * @var string
     */
    protected $baseId;

    /**
     * Instance data from module
     * Gets passed through to section handler
     * @var array
     */
    protected $data;


    /**
     * @param $structure
     * @return mixed|void
     */
    public function setStructure( $structure )
    {
        $this->structure = $structure;
    }

    /**
     * Wrapper to output methods
     * @param $baseId
     * @param $data
     * @return mixed|void
     */
    public function render( $baseId, $data )
    {
        if (!is_array( $this->structure )) {
            return;
        }

        $this->baseId = $baseId;
        $this->data = $data;

        $this->tabNavigation();
        $this->tabContainers();

    }

    /**
     * Renders the tab navigation markup
     */
    public function tabNavigation()
    {

        echo "<div class='kb_fieldtabs kb-field--tabs'>";
        echo "<ul>";


        foreach ($this->structure as $section) {

            if ($section->getNumberOfVisibleFields() > 0) {
                echo "<li><a href='#tab-{$section->getID()}'>{$section->getLabel()}</a></li>";
            }
        }
        echo '</ul>';

    }

    /**
     * Renders the tab containers
     */
    public function tabContainers()
    {
        foreach ($this->structure as $section) {
            if ($section->getNumberOfVisibleFields() > 0) {
                echo "<div id='tab-{$section->getID()}'>";
                $section->render( $this->baseId, $this->data );
                echo "</div>";
            } else {
                $section->render( $this->baseId, $this->data );
            }
        }
        echo "</div>";

    }

}
