<?php

namespace Kontentblocks\Fields;

use Kontentblocks\Modules\Module;
use Reframe\Kontentblocks\Kontentblocks;

/**
 * ModuleFieldController
 * Purpose of this class:
 * Connecting fields to a module and offering an API to interact with
 * fields and the underlying structure.
 *
 * There are two different cases which are handled by this class:
 * 1) Backend: preparing fields and initiate the rendering of the field output
 * 2) Frontend: Setting fields up.
 *
 * Instantiated by Kontentblocks\Modules\Module if fields() method is present
 * in extending class
 *
 * @see Kontentblocks\Modules\Module::__cosntruct()
 * @param \Kontentblocks\Modules\Module
 */
class ModuleFieldController extends AbstractFieldController
{

    /**
     * @var \Kontentblocks\Fields\FieldRendererTabs
     */
    protected $renderEngineClass = 'Kontentblocks\Fields\FieldRendererTabs';

    /**
     * Constructor
     * @param \Kontentblocks\Modules\Module
     * @since 1.0.0
     */
    public function __construct( Module $Module )
    {
        $this->baseId = $Module->getId();
        $this->data = $Module->moduleData;
        $this->Module = $Module;
    }

    /**
     * Creates a new section if there is not already one with the same id
     * or returns the section if exists
     * @param string $id
     * @param array $args
     * @param Kontentblocks\Modules\Module
     * @return object
     * @since 1.0.0
     */
    public function addGroup( $id, $args = array() )
    {
        if (!$this->idExists( $id )) {
            $this->Structure[$id] = new FieldSection(
                $id,
                $args,
                $this->Module->envVars,
                $this->Module,
                $this->Module->getModuleId()
            );
        }
        return $this->Structure[$id];

    }


    /**
     * Backend render method | Endpoint
     * output gets generated by attached render object
     * defaults to tabs
     * called by Kontentblocks\Modules\Module::options()
     * if not overridden b extending class
     * @see Kontentblocks\Modules\Module::form
     * @return void
     * @since 1.0.0
     */
    public function renderFields()
    {
        $Renderer = new $this->renderEngineClass( $this->baseId, $this->Structure );
        return $Renderer->render( $this->data );
    }


    /**
     * set Class which handles form creation for fields
     * @param $class
     */
    public function setRenderEngineClass( $class )
    {
        //@TODO verify against abstract/interface
        $this->renderEngineClass = $class;
    }
}
