language: php

sudo: false

php:
    - 5.4

env:
    - WP_VERSION=latest WP_MULTISITE=0
    - WP_VERSION=3.9 WP_MULTISITE=0

before_script:
    - mysql -e 'create database wordpress_test;'
    - 'bin/install-wp-tests.sh wordpress_test root '' 127.0.0.1 $WP_VERSION'

script: phpunit
